import json

translations = {
    "fr.json": {
        "allBookings": "Toutes les réservations",
        "showingResults": "Affichage de {count} résultat(s)",
        "searchBooking": "Rechercher une réservation",
        "tableSpace": "Espace",
        "tableAmount": "Montant",
        "tableDate": "Date",
        "tablePaymentStatus": "Statut de paiement",
        "tableAction": "Action",
        "noBookingsMatch": "Aucune réservation ne correspond à votre recherche.",
        "viewAction": "Voir",
        "bookingDetailsTitle": "Détails de la réservation",
        "spaceLabel": "Espace",
        "spaceTypeLabel": "Type d'espace",
        "checkInLabel": "Arrivée",
        "checkOutLabel": "Départ",
        "durationLabel": "Durée",
        "amountPaidLabel": "Montant payé",
        "cancellationPeriodLabel": "Période d'annulation",
        "datePaidLabel": "Date de paiement",
        "reportProperty": "Signaler cette propriété",
        "downloadInvoice": "Télécharger la facture",
        "cancelBooking": "Annuler la réservation",
        "filterBookings": "Filtrer",
        "filterStatus": "Statut",
        "filterSpaceType": "Type d'espace",
        "filterDate": "Date",
        "statusConfirmed": "Confirmé",
        "statusCompleted": "Terminé",
        "statusCancelled": "Annulé",
        "statusPending": "En attente",
        "statusPaid": "Payé",
        "typeBoardroom": "Salle de réunion",
        "typeShortlet": "Location courte durée",
        "typeOffice": "Bureau",
        "dateStart": "Date de début",
        "dateEnd": "Date de fin",
        "filterReset": "Réinitialiser",
        "filterApply": "Appliquer"
    },
    "es.json": {
        "allBookings": "Todas las reservas",
        "showingResults": "Mostrando {count} resultado(s)",
        "searchBooking": "Buscar reserva",
        "tableSpace": "Espacio",
        "tableAmount": "Monto",
        "tableDate": "Fecha",
        "tablePaymentStatus": "Estado de pago",
        "tableAction": "Acción",
        "noBookingsMatch": "Ninguna reserva coincide con su búsqueda.",
        "viewAction": "Ver",
        "bookingDetailsTitle": "Detalles de la reserva",
        "spaceLabel": "Espacio",
        "spaceTypeLabel": "Tipo de espacio",
        "checkInLabel": "Llegada",
        "checkOutLabel": "Salida",
        "durationLabel": "Duración",
        "amountPaidLabel": "Monto pagado",
        "cancellationPeriodLabel": "Período de cancelación",
        "datePaidLabel": "Fecha de pago",
        "reportProperty": "Reportar esta propiedad",
        "downloadInvoice": "Descargar factura",
        "cancelBooking": "Cancelar reserva",
        "filterBookings": "Filtrar",
        "filterStatus": "Estado",
        "filterSpaceType": "Tipo de espacio",
        "filterDate": "Fecha",
        "statusConfirmed": "Confirmado",
        "statusCompleted": "Completado",
        "statusCancelled": "Cancelado",
        "statusPending": "Pendiente",
        "statusPaid": "Pagado",
        "typeBoardroom": "Sala de juntas",
        "typeShortlet": "Alquiler a corto plazo",
        "typeOffice": "Oficina",
        "dateStart": "Fecha de inicio",
        "dateEnd": "Fecha de fin",
        "filterReset": "Restablecer",
        "filterApply": "Aplicar"
    },
    "ko.json": {
        "allBookings": "모든 예약",
        "showingResults": "{count}개의 결과 표시 중",
        "searchBooking": "예약 검색",
        "tableSpace": "공간",
        "tableAmount": "금액",
        "tableDate": "날짜",
        "tablePaymentStatus": "결제 상태",
        "tableAction": "작업",
        "noBookingsMatch": "검색어와 일치하는 예약이 없습니다.",
        "viewAction": "보기",
        "bookingDetailsTitle": "예약 세부 정보",
        "spaceLabel": "공간",
        "spaceTypeLabel": "공간 유형",
        "checkInLabel": "체크인",
        "checkOutLabel": "체크아웃",
        "durationLabel": "기간",
        "amountPaidLabel": "결제 금액",
        "cancellationPeriodLabel": "취소 기간",
        "datePaidLabel": "결제일",
        "reportProperty": "이 숙소 신고하기",
        "downloadInvoice": "청구서 다운로드",
        "cancelBooking": "예약 취소",
        "filterBookings": "필터",
        "filterStatus": "상태",
        "filterSpaceType": "공간 유형",
        "filterDate": "날짜",
        "statusConfirmed": "확정됨",
        "statusCompleted": "완료됨",
        "statusCancelled": "취소됨",
        "statusPending": "대기 중",
        "statusPaid": "결제됨",
        "typeBoardroom": "회의실",
        "typeShortlet": "단기 임대",
        "typeOffice": "사무실",
        "dateStart": "시작 날짜",
        "dateEnd": "종료 날짜",
        "filterReset": "초기화",
        "filterApply": "적용"
    },
    "hi.json": {
        "allBookings": "सभी बुकिंग",
        "showingResults": "{count} परिणाम दिखा रहे हैं",
        "searchBooking": "बुकिंग खोजें",
        "tableSpace": "जगह",
        "tableAmount": "रकम",
        "tableDate": "तारीख",
        "tablePaymentStatus": "भुगतान की स्थिति",
        "tableAction": "कार्रवाई",
        "noBookingsMatch": "आपकी खोज से मेल खाने वाली कोई बुकिंग नहीं है।",
        "viewAction": "देखें",
        "bookingDetailsTitle": "बुकिंग का विवरण",
        "spaceLabel": "जगह",
        "spaceTypeLabel": "जगह का प्रकार",
        "checkInLabel": "चेक इन",
        "checkOutLabel": "चेक आउट",
        "durationLabel": "अवधि",
        "amountPaidLabel": "भुगतान की गई राशि",
        "cancellationPeriodLabel": "रद्दीकरण अवधि",
        "datePaidLabel": "भुगतान की तारीख",
        "reportProperty": "इस संपत्ति की रिपोर्ट करें",
        "downloadInvoice": "चालान डाउनलोड करें",
        "cancelBooking": "बुकिंग रद्द करें",
        "filterBookings": "फ़िल्टर",
        "filterStatus": "स्थिति",
        "filterSpaceType": "जगह का प्रकार",
        "filterDate": "तारीख",
        "statusConfirmed": "पुष्टि की गई",
        "statusCompleted": "पूरा हुआ",
        "statusCancelled": "रद्द किया गया",
        "statusPending": "लंबित",
        "statusPaid": "भुगतान किया गया",
        "typeBoardroom": "बोर्डरुम",
        "typeShortlet": "शॉर्टलेट",
        "typeOffice": "कार्यालय",
        "dateStart": "शुरू होने की तारीख",
        "dateEnd": "समाप्ति की तारीख",
        "filterReset": "रीसेट",
        "filterApply": "लागू करें"
    },
    "en.json": {
        "statusPending": "Pending",
        "statusPaid": "Paid"
    }
}

for filename, translation_data in translations.items():
    filepath = f"i18n/dictionaries/{filename}"
    try:
        with open(filepath, 'r') as f:
            data = json.load(f)
        
        for k, v in translation_data.items():
            data["settings"][k] = v
            
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write('\n')
            
    except Exception as e:
        print(f"Failed to process {filename}: {e}")

print("Translations applied successfully.")
